# 1. URL de conexión (USA "db" porque es el nombre del servicio en la red de Docker)
spring.datasource.url=jdbc:mysql://localhost:3307/quantia_db?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root

# 2. Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Hibernate y JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Forzamos el dialecto para evitar el error "Unable to determine Dialect"
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Le damos 1 minuto de gracia para que MySQL arranque antes de fallar
spring.datasource.hikari.initialization-fail-timeout=60000
# --- CONFIGURACIÓN SWAGGER ---
# Cambia la URL por defecto a una más corta
springdoc.swagger-ui.path=/swagger-ui.html

# Ordena los endpoints por método (GET, POST, etc.)
springdoc.swagger-ui.operationsSorter=method

# Activa la interfaz de usuario de Swagger
springdoc.swagger-ui.enabled=true