# 1. URL de conexión (quantia_db es el nombre que pusimos en el script SQL)
spring.datasource.url=jdbc:mysql://localhost:3306/quantia_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=idipro9087

# 2. Driver de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Hibernate: 'update' crea las tablas si no existen o las actualiza sin borrar datos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 4. Activar Hilos Virtuales (Aprovechando Java 21 para Quantia)
spring.threads.virtual.enabled=true

spring.security.user.name=user
spring.security.user.password=123
